### ISSUE TITLE
feat: add inverted speech bubble generator

### ISSUE THREAD

**Issue by insertish** [ShaksterNano/Media-Manipulator-Discord-Bot#1]
make do like this

![](https://media.discordapp.net/attachments/273777356508758016/956627606676049981/screw.gif)
![](https://media.discordapp.net/attachments/929807268994744340/965675775669964830/lizardplane_1.gif)

and not like this

![image](https://user-images.githubusercontent.com/38285861/164300114-91dd6686-7107-438c-b9e5-39919b99cca6.png)

or both

**Comment by ShaksterNano** [comment]
https://media.discordapp.net/attachments/927613139116249181/965608843293896784/borgar_stretched.gif

**Comment by JSusak** [comment]
True

**Comment by ShaksterNano** [comment]
![image](https://user-images.githubusercontent.com/54268387/164300413-f87b3e4d-87e9-4b6f-a7fd-126542376f3c.png)

**Comment by janderedev** [comment]
> ![image](https://user-images.githubusercontent.com/54268387/164300413-f87b3e4d-87e9-4b6f-a7fd-126542376f3c.png)

![image](https://user-images.githubusercontent.com/26145882/164300736-8892d2e4-f307-48c6-b5e7-6165efa1533a.gif)

**Comment by ShaksterNano** [comment]
![image](https://user-images.githubusercontent.com/54268387/164301414-3790e6ac-f744-488c-9cab-0882cf7d1bea.png)

**Comment by ShaksterNano** [comment]
![image0-48_speech_bubbled](https://user-images.githubusercontent.com/54268387/164301516-831149be-d71e-4025-8a1d-65bdc0661226.gif)

**Comment by ShaksterNano** [comment]
i have no clue how to do this lol

**Comment by insertish** [comment]
![17gpkr1g7qu81.jpg](https://user-images.githubusercontent.com/38285861/164827126-c04d01c6-ae0d-4f93-8b35-aba6370e7a30.jpg)

**Comment by ShaksterNano** [comment]
![image](https://user-images.githubusercontent.com/54268387/164915557-e3319c1d-d45c-4486-a184-a8f88c62d1c6.png)
oop
