### ISSUE TITLE
feat: uncaption images with caption

### ISSUE THREAD

**Issue by insertish** [ShaksterNano/Media-Manipulator-Discord-Bot#10]
Captions always have white at the top so it should be sufficient to just read pixels vertically down the side until the first non white colour is found

**Comment by ShaksterNano** [comment]
![image0-3_speech_bubbled](https://user-images.githubusercontent.com/54268387/169100600-cd6f65f6-55ef-4395-a646-649385fa084f.gif)

**Comment by Rahul-Imran** [comment]
https://media.discordapp.net/attachments/717498714259980378/961424172205105162/image2-1-2.gif

**Comment by Ronen09** [comment]
sus
