### ISSUE TITLE
feat: %sonic (at request of fox)

### ISSUE THREAD

**Issue by insertish** [ShaksterNano/Media-Manipulator-Discord-Bot#3]
![](https://cdn.discordapp.com/attachments/939951857873350746/968156853466984558/unknown.png)

Direct Link: https://cdn.discordapp.com/attachments/939951857873350746/968156853466984558/unknown.png

**Comment by ShaksterNano** [comment]
https://github.com/esmBot/esmBot/blob/master/assets/images/sonic.jpg
![image](https://user-images.githubusercontent.com/54268387/165112354-c87ba082-daaf-47e7-963f-92b93d048a63.png)
