### ISSUE TITLE
feat: add %impact

### ISSUE THREAD

**Issue by Rahul-Imran** [ShaksterNano/Media-Manipulator-Discord-Bot#7]
Write impact font on an image such as:
![image](https://user-images.githubusercontent.com/25961265/166102652-5ad03e94-4fb8-414b-9660-d4f4499314e3.png)

**Comment by Rahul-Imran** [comment]
@ShaksterNano hurry up and add this smh

**Comment by ShaksterNano** [comment]
![unknown_speech_bubbled](https://user-images.githubusercontent.com/54268387/170988364-a9ffd8b8-a810-44e3-88a4-e3d895d8673e.gif)
